language: node_js

node_js:
  - "stable"

dist: trusty
sudo: true

cache:
  yarn: true
  directories:
    - .gitmtimecache
    - .eslintcache
    - .jestcache
    - node_modules

env:
  global:
    # link to our bundled version yarn
    - PATH=$TRAVIS_BUILD_DIR/bin:$PATH

stages:
  - name: test
  - name: deploy
    if: "type != pull_request AND branch = master"

# build stages
jobs:
  fast_finish: true
  include:
    # This is really the compile step but we run in it parallel with the tests anyway
    - stage: test
      script: yarn test
    - stage: test
      script: yarn lint:base -- . 
    - stage: test
      script: yarn flow check
    - stage: deploy
      provider: pages
      skip-cleanup: true
      github-token: $github_token
      local-dir: build

